name: Deploy to Pages

on: workflow_dispatch

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  deploy:
    name: Generate Build and Deploy to GitHub Pages
    needs: [checks]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Build app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Push README.md
        run: |
          git add README.md
          git commit -m "docs: update project info"
          git push
