name: 'Lighthouse Badges'

on:
  - workflow_call
  - workflow_dispatch

permissions:
  contents: read

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Generate badges
        run: npm run lighthouse-badge

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes"
          else
            git add docs/pagespeed.svg
            git commit -m "Update pagespeed badge"
            git pull --rebase
            git push
          fi
